// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.ptg.domain;

import java.util.Date;
import nc.noumea.mairie.ptg.domain.Droit;
import nc.noumea.mairie.ptg.domain.DroitsAgent;

privileged aspect DroitsAgent_Roo_JavaBean {
    
    public Droit DroitsAgent.getDroit() {
        return this.droit;
    }
    
    public void DroitsAgent.setDroit(Droit droit) {
        this.droit = droit;
    }
    
    public Integer DroitsAgent.getIdAgent() {
        return this.idAgent;
    }
    
    public void DroitsAgent.setIdAgent(Integer idAgent) {
        this.idAgent = idAgent;
    }
    
    public String DroitsAgent.getCodeService() {
        return this.codeService;
    }
    
    public void DroitsAgent.setCodeService(String codeService) {
        this.codeService = codeService;
    }
    
    public String DroitsAgent.getLibelleService() {
        return this.libelleService;
    }
    
    public void DroitsAgent.setLibelleService(String libelleService) {
        this.libelleService = libelleService;
    }
    
    public Date DroitsAgent.getDateModification() {
        return this.dateModification;
    }
    
    public void DroitsAgent.setDateModification(Date dateModification) {
        this.dateModification = dateModification;
    }
    
}
