// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.ptg.domain;

import nc.noumea.mairie.ptg.domain.EtatPayeur;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EtatPayeur_Roo_Configurable {
    
    declare @type: EtatPayeur: @Configurable;
    
}
