// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.ptg.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nc.noumea.mairie.ptg.domain.RefEtat;

privileged aspect RefEtat_Roo_Jpa_Entity {
    
    declare @type: RefEtat: @Entity;
    
    declare @type: RefEtat: @Table(name = "PTG_REF_ETAT");
    
}
