// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.ptg.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nc.noumea.mairie.ptg.domain.TypePointage;

privileged aspect TypePointage_Roo_Jpa_Entity {
    
    declare @type: TypePointage: @Entity;
    
    declare @type: TypePointage: @Table(name = "PTG_TYPE_POINTAGE");
    
}
