language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: m/+fFvBo4iZxoHgCH2CrwxZts/shrArLzZ9c2w5BOoE4gpv3m/Ikr5dULq3IKMCi/kq55P4heaP3mE7iFg7KaqTNPz42CK2TvMElFxKtWKEMO7UXha4iJYTsNl0tO4wkupHBb+pLrJDJ7tl910pIg61U1dzhQerA/4oWklwIquD0+M7jVDoj0rzSmVx/kLbi7pEsFf52GMrWDjc5F1D6vgapgHyG6plFQV1Aika1wbfipzJKW6Gk3/c5IXl8P3FRseGLTSJvLtxd4wJC9JCLF4q/wAPoFBHr5Skbxr96EXu2L7ltxF5hD5LfSRy0XxAG/ChOxpmkg7WyYjVueOnXR24HTQbkhRg/CJSt5CRkxog2zvjkYlI+0MynqaAwmqnt0cEJ2BUDlI54BgSAcvChzqAKVVfvO/CKrMi0F29mScQgv/DL2B+ZcKPXvOXHCg3F6ITptjfX9zaT57ZCqmG5nz7neGpZKgpBqFjtsq51E7GBN7w6KfmAqiRyTGMRDyF9bBngm/ihmWVrQ/TEKx7yMQJKlVDcCKzkO2Au95DJAqjDYtJz+viUkhEAvSwWT/baA4+Hiet3oubRP77WeFHMIX7YzNAXunZviT56jKkwgX2bnoiSxkNZkuNXtw7wxxtd/10VgX0wST4Sy3nJrK8sJAZg3FOP3/xn6Lzl43dygX0=
  - secure: QOUlEWuTiISkqRj3wQcR6dcLltjQkMstJl6X2GJkI52QUnBPVDJLRjN1/IdlQuLjO1X3+I8G3ligPTpJyYnFHRQnxyIPQ9kLjIoQtdjYW9232l3sAmVquziUACBeImcHmFPRxiqynx4joXMFuoPZhwn0l+nf1whzJ0PH4ACpXJSCPd//AqIaDRP++OrFHVEq+T2/Q4MyZIdMzcazKxj7Iy5cOnaegqFoq0WaDcZMIzJE+v9tfHyDxrydX/bM2tqdJhz8KMAxHEOeTE3olJcodoLfkhK4TKlkZji4IerNqdl5hFTWPynyKfMl574yEh25MnxMnXm6jMbVQN6OBG9ggLeGH7Mu+EO7qAaQt5pAW3fLacmDvbKAx6KLfKKJ13nYrPzCIPI124CDsmV+VplasxMydwFMckwA3jkEHo4LOmtURTPB7kjN+s5b+SsIwS0Mz7wOY52Hg70Cm6TBDRKC3+VX4j27/NrawI/h5T7TD1WoZCcUJR1epP4ULJQPJcU9T4MiuxVDY+m4HtdN4FQG/ZYUvjmmeaBeBI5FxNtfXomUH6xr2fNRw6Vt2L6hp0KHGmis7CrQ3sk9opLp4HRilEvTANynVdLqDlVzKW0YhKzb6QtuWOG2AYYGU31wk5Hpwwx+9J19JUwyjXh3KQCxVYsvv7qZCBnjnZQUBXY9xPI=
  - secure: wy1TFq9Z9DdV6etQjItlg5XVC6ksG9UzbQIq0nwPKejlAyo3kmuN1I5TrJjDZFjaeLVhkqnM4RcPSk12VR2BSuRABJ59f67/fqtXGtx5UMttzbXBvzCrE4DyIglrzCwYg8g5d8NtGtOwJ61mT0sWKCrjnJ4xV9HdR83afwUd6nJRhkbiTVZ+ATIQ8JnrNCGROadGUJNf+pzDFCvv0DQJI9U8H4cRBza6rb7fID7CMM+ARN8/N3lA+iCLaEtKDWQaIlFdTR6KguM/p+2+yh7mg5tT2W+Oc8wxme1GtepGBDnzXoIopxYhfvR5yhwRs949MyuOlwfh1smBeQSEqZR0hg3Tcpz8AjnBt2cV2bT1AVL5KwCu4CU6m2uhIcf25qUCXOSFGzJ2QhUMnOyRrR2SfXC4l648K9B6kLNoDbk8PMAvsZaGyI/UIeaOhS19XQcXLLc2EZkYNRQz0wsfax3UApPIqC6aJ2i1WcR/QSLdGQmctfhEYKmR/vzeC42aASoS7COsEuwMXbdSino3JY610XJfVMFIj46GUBb2EPFQj9AaThNrkcrUP6AIbojSI8ixjh81rdjrjAWlX578N9KvTjKxBREeEXBoS27vHBi72EBqN2QPK/L9NbN5gaV9C7b865Gli1PsGoFsU3prw8AwZFeqPlb2bSYAfA+2lp9ViVU=
before_install:
- export TZ=Pacific/Noumea
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: e4duUum4FfhftR1GBuAWWth+afZrU/71EGLOki/onBqoZRE2xFfdqCO/BQvuLAsiwrc/jnXZBcePGFNxZ+mpsfVB2h3grz0x00tAn+oWcvSlJ/NJTn83ufb9+B3VeElpak1iGizsUkSv7sJZtOG4vnqUk+8kYYqOJ5us6CDe3Ld1rxLdKXGPTYXsYjdq8gKDbW82RpyjmviK2g3SOONKyXdWEeqN1adpuSaqoPL03+IITkuESih7oRddL8AafmC22x/8vIRnZ7hC3J9t5Iib8I69hh7a/SAVWAZ0IXLz4d8h9A3L8IYNRJfI2jwAfZl+TKzXIsC1zN9a1Nd8JbpXcesXPnP5J0zQcVBRW0DJik/G+MjGVsnW646nur/Q5OVqh2FDkiHq5Wje+jhEKf8wdtCiYyCb50tJesGFyhw5A55PdvSb1bxLGdRXDX3in7lDC+xRCG39sPX+3SpTnZ2+dYbjdIa43FRTtLbAipA6X2MXIpd66eMaGYl9nIH8N7lf5mVuIjFWC08Bm2dn64tW7FXA2e22A6v+CxRoog4Rb3TTKAeYOce8m/OuaTz0T/RE8M28jntIsSWhesnle8XDk7pF7f/86ZqVHCA+bv5rvsXFNABFmrSiVfuEaaCSaaoWRqB3OVKRiRiOlImuchCBIrlytFyw3vpVPIbBiI9u5I8=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-ptg-ws
notifications:
  slack:
    secure: O/+2Lw2KUwP3vClLdbk7cHy/r4weTe0iI9RUxZrIYKF4OQ10L5UcBo+VD8e2yyV9zUTtubRCjAEFyn0ZMfNKOXDNjnQx0MF7YHmiCQBl2worhI31rvsEui2PLyBmUJ7T+X8TPQjceh9GvPHnzxyZ6Ot5imVT7hRzbD4KuM39q720wT0xPsM67YfmDDr795rllOEpvsXvFNd42ym3e+/Z85SwYbsFc+RyEy/PuxoYujniLxeeC4Dsg7yxVMEgS+1AD5UevKCRvD6nB1z2Ew3C+zVaBsuQ79n7lxZhAe1fMCvJ4tTU3c6XuH5LPyU3G6PyEWzBPoTY1oGV4erK3EXZFUFio06hl9y5eJLutg24QISRPwX1R1m5siqtnqxpgaSCOX1q3w/jxxDaDR6uPtqUw+BrHU5F/Zr4a1VRpQvZHA2XzqVN6A35F5yQhGQMyp108V6tn/gXFqOarHdtQkBxNYmzHyfXtetAqYurECrTjPzatDhlNnIJtZ21f/c86R5gllbYnbxpmnlzcHGfv4IWTyakZC4/kcTC3BCTCXBYd08+fSIMoi3qRsu7GJlRQ1Q/j27hNQtvoPaKL8dxsJmXVqaRGTm/Lmsti/W1NrqeSi87ACSQ8kHrvOeq+wKpWRxyBaaNbUqR20QIpB/xGJJZ2zFX387KCgF+XKQn7Smchn4=
