// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.sirh.domain;

import nc.noumea.mairie.sirh.domain.PrimePointage;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PrimePointage_Roo_Configurable {
    
    declare @type: PrimePointage: @Configurable;
    
}
