// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nc.noumea.mairie.domain.Spabsen;

privileged aspect Spabsen_Roo_Jpa_Entity {
    
    declare @type: Spabsen: @Entity;
    
    declare @type: Spabsen: @Table(name = "SPABSEN");
    
}
