// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nc.noumea.mairie.domain.Spbase;

privileged aspect Spbase_Roo_Jpa_Entity {
    
    declare @type: Spbase: @Entity;
    
    declare @type: Spbase: @Table(schema = "MAIRIE", name = "SPBASE");
    
}
