// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.domain;

import nc.noumea.mairie.domain.Spcong;
import nc.noumea.mairie.domain.SpcongId;

privileged aspect Spcong_Roo_JavaBean {
    
    public SpcongId Spcong.getId() {
        return this.id;
    }
    
    public void Spcong.setId(SpcongId id) {
        this.id = id;
    }
    
}
