// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nc.noumea.mairie.domain.Sppprm;

privileged aspect Sppprm_Roo_Jpa_Entity {
    
    declare @type: Sppprm: @Entity;
    
    declare @type: Sppprm: @Table(name = "SPPPRM");
    
}
