// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.domain;

import nc.noumea.mairie.domain.SpWFPaie;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SpWFPaie_Roo_Configurable {
    
    declare @type: SpWFPaie: @Configurable;
    
}
