// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.domain;

import javax.persistence.Entity;
import javax.persistence.Table;
import nc.noumea.mairie.domain.SpWFPaie;

privileged aspect SpWFPaie_Roo_Jpa_Entity {
    
    declare @type: SpWFPaie: @Entity;
    
    declare @type: SpWFPaie: @Table(name = "SPWFPAIE");
    
}
