----------------------------------------------------------------
-- connecte en PTG_ADM
----------------------------------------------------------------

ALTER TABLE PTG_ADM.PTG_DROITS_AGENT DROP COLUMN ID_AGENT_APPROBATEUR;
ALTER TABLE PTG_ADM.PTG_DROITS_AGENT DROP COLUMN ID_DROITS_PROFIL;
ALTER TABLE PTG_DROITS_AGENT ADD (ID_DELEGATAIRE NUMBER(38,0));
ALTER TABLE PTG_ADM.PTG_DROITS_AGENT ADD (IS_APPROBATEUR NUMBER(1,0) default 0 not null);
ALTER TABLE PTG_ADM.PTG_DROITS_AGENT ADD (IS_OPERATEUR NUMBER(1,0) default 0 not null);
DROP TABLE PTG_ADM.PTG_DROITS_PROFIL;

ALTER TABLE PTG_ADM.PTG_ETAT_POINTAGE MODIFY ETAT NUMBER(2,0) default 1;

ALTER TABLE PTG_ADM.PTG_POINTAGE ADD ID_REF_PRIME NUMBER(38,0);
ALTER TABLE PTG_ADM.PTG_POINTAGE ADD CONSTRAINT FK_PTG_REF_PRIME
   foreign key (ID_REF_PRIME)
   references PTG_REF_PRIME (ID_REF_PRIME);
ALTER TABLE PTG_POINTAGE ADD (IS_HSUP_PAYEE NUMBER(1,0));
ALTER TABLE PTG_POINTAGE ADD (IS_ABS_CONCERTEE NUMBER(1,0));
ALTER TABLE PTG_ADM.PTG_POINTAGE ADD ID_COMMENT_MOTIF NUMBER(38,0);
ALTER TABLE PTG_ADM.PTG_POINTAGE ADD CONSTRAINT FK_PTG_COM_MOTIF
   foreign key (ID_COMMENT_MOTIF)
   references PTG_COMMENT (ID_COMMENT);
ALTER TABLE PTG_ADM.PTG_POINTAGE ADD ID_COMMENT_COMMENTAIRE NUMBER(38,0);
ALTER TABLE PTG_ADM.PTG_POINTAGE ADD CONSTRAINT FK_PTG_COM_COM
   foreign key (ID_COMMENT_COMMENTAIRE)
   references PTG_COMMENT (ID_COMMENT);
 
-----------RENOMMAGE DE LA TABLE PTG_TYPE_POINTAGE
ALTER TABLE PTG_ADM.PTG_TYPE_POINTAGE RENAME TO PTG_ADM.PTG_REF_TYPE_POINTAGE;
alter table PTG_ADM.PTG_REF_TYPE_POINTAGE RENAME COLUMN ID_TYPE_POINTAGE TO ID_REF_TYPE_POINTAGE;

create public synonym PTG_REF_TYPE_POINTAGE for PTG_REF_TYPE_POINTAGE;


----Clé étrangère
ALTER TABLE PTG_ADM.PTG_ETAT_POINTAGE ADD CONSTRAINT FK_PTG_ETAT_POINTAGE
   foreign key (ETAT)
   references PTG_REF_ETAT (ID_REF_ETAT);