----------------------------------------------------------------
-- connecte en PTG_ADM
----------------------------------------------------------------

-- PTG_TYPE_POINTAGE
INSERT INTO PTG_ADM.PTG_TYPE_POINTAGE (ID_TYPE_POINTAGE, LABEL) VALUES ('1', 'Absence');
INSERT INTO PTG_ADM.PTG_TYPE_POINTAGE (ID_TYPE_POINTAGE, LABEL) VALUES ('2', 'Heure Supplémentaire');
INSERT INTO PTG_ADM.PTG_TYPE_POINTAGE (ID_TYPE_POINTAGE, LABEL) VALUES ('3', 'Prime');

-- PTG_REF_PRIME
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7120,'PRIME DE PERMANENCE','Prime forfaitaire mensuelle de 3000F',0,0, 'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7120,'PRIME DE PERMANENCE','Prime forfaitaire mensuelle de 3000F',0,0, 'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7120,'PRIME DE PERMANENCE','Prime forfaitaire mensuelle de 3000F',0,0, 'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7121,'INDEMNITE D''ASTREINTE','Prime forfaitaire journalière de 3000F',0,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7121,'INDEMNITE D''ASTREINTE','Prime forfaitaire journalière de 3000F',0,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7121,'INDEMNITE D''ASTREINTE','Prime forfaitaire journalière de 3000F',0,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7123,'INDEMNITE DE PERMANENCE CFM','Prime forfaitaire journalière de 3000F',0,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7123,'INDEMNITE DE PERMANENCE CFM','Prime forfaitaire journalière de 3000F',0,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7123,'INDEMNITE DE PERMANENCE CFM','Prime forfaitaire journalière de 3000F',0,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7650,'INDEMNITE FORFAITAIRE TRAVAIL DE NUIT','Prime forfaitaire de 10000F/nuit ',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7651,'INDEMNITE FORFAITAIRE TRAVAIL DE NUIT DJF','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7652,'INDEMNITE FORFAITAIRE TRAVAIL DJF','Prime forfaitaire de 8500F par dimanche ou JF travaillé, quelque soit le nb d''heures travaillées',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7701,'PRIME DE TRAVAUX INSALUBRES ET DANGEREUX','Egale à 500F/heure * un taux (100%, 50%, ou 25%) inclus dans les spécificités de la FP. Elle est perçue même en période de congés',1,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7701,'PRIME DE TRAVAUX INSALUBRES ET DANGEREUX','Prime perçue pour chaque heure travaillée (base horaire journalière + HS), toutes activités confondues (même en période de congé), à l''exception des repos compensateurs (A51) et absences administratives (R50)',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7704,'INDEMNITE DE PANIER','',2,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7704,'INDEMNITE DE PANIER','',2,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7704,'INDEMNITE DE PANIER','',2,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7705,'PRIME D''ASTREINTE','Prime forfaitaire de 2000F/astreinte',0,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7705,'PRIME D''ASTREINTE','Prime forfaitaire de 2000F/astreinte',0,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7705,'PRIME D''ASTREINTE','Prime forfaitaire de 2000F/astreinte',0,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7708,'PRIME D''ASTREINTE HORAIRE','Prime forfaitaire horaire',1,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7709,'INDEMNITE PARTICIPATION AUTOPSIES TARIF I','Prime forfaitaire de 12000F/autopsie',2,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7709,'INDEMNITE PARTICIPATION AUTOPSIES TARIF I','Prime forfaitaire de 12000F/autopsie',2,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7709,'INDEMNITE PARTICIPATION AUTOPSIES TARIF I','Prime forfaitaire de 12000F/autopsie',2,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7710,'INDEMNITE PARTICIPATION AUTOPSIES TARIF II','Prime forfaitaire de 15000F/autopsie',2,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7710,'INDEMNITE PARTICIPATION AUTOPSIES TARIF II','Prime forfaitaire de 15000F/autopsie',2,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7710,'INDEMNITE PARTICIPATION AUTOPSIES TARIF II','Prime forfaitaire de 15000F/autopsie',2,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7711,'INDEMNITE HORAIRE TRAVAIL DE NUIT DPM','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7711,'INDEMNITE HORAIRE TRAVAIL DE NUIT DPM','',null,1,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7711,'INDEMNITE HORAIRE TRAVAIL DE NUIT DPM','',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7712,'INDEMNITE HORAIRE TRAVAIL DJF DPM','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7712,'INDEMNITE HORAIRE TRAVAIL DJF DPM','',null,1,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7712,'INDEMNITE HORAIRE TRAVAIL DJF DPM','',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7713,'INDEMNITE DE PANIER DPM','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7713,'INDEMNITE DE PANIER DPM','',null,1,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7713,'INDEMNITE DE PANIER DPM','',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7715,'INDEMNITE DE ROULEMENT','Les agents "de terrain" de la DPM fonctionnent par "roulements" sur une journée de 24h et saisissent ainsi une "indemnité de roulement" sous la forme d’heures de début et de fin de travail. Cette indemnité n’est pas valorisée elle-même financièrement mais sert juste à déduire  les 7711, 7712 et 7713',3,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7715,'INDEMNITE DE ROULEMENT','Les agents "de terrain" de la DPM fonctionnent par "roulements" sur une journée de 24h et saisissent ainsi une "indemnité de roulement" sous la forme d’heures de début et de fin de travail. Cette indemnité n’est pas valorisée elle-même financièrement mais sert juste à déduire  les 7711, 7712 et 7713',3,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7715,'INDEMNITE DE ROULEMENT','Les agents "de terrain" de la DPM fonctionnent par "roulements" sur une journée de 24h et saisissent ainsi une "indemnité de roulement" sous la forme d’heures de début et de fin de travail. Cette indemnité n’est pas valorisée elle-même financièrement mais sert juste à déduire  les 7711, 7712 et 7713',3,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7720,'INDEMNITE TVX INSAL. DANG. 100%','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7720,'INDEMNITE TVX INSAL. DANG. 100%','',null,1,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7720,'INDEMNITE TVX INSAL. DANG. 100%','',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7721,'INDEMNITE TVX INSAL. DANG. 50%','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7721,'INDEMNITE TVX INSAL. DANG. 50%','',null,1,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7721,'INDEMNITE TVX INSAL. DANG. 50%','',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7722,'INDEMNITE TVX INSAL. DANG. 25%','',null,1,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7722,'INDEMNITE TVX INSAL. DANG. 25%','',null,1,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7722,'INDEMNITE TVX INSAL. DANG. 25%','',null,1,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7731,'INDTE FORFAITAIRE DE DERANGEMENT','Prime forfaitaire horaire',1,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7731,'INDTE FORFAITAIRE DE DERANGEMENT','Prime forfaitaire horaire',1,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7731,'INDTE FORFAITAIRE DE DERANGEMENT','Prime forfaitaire horaire',1,0,'CC');

INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7750,'INDEMNITE D''ACTIVITE','Anciennement prime de cimetière, calculée dans GIRAF selon un indice de cherté de vie',0,0,'F');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7750,'INDEMNITE D''ACTIVITE','Anciennement prime de cimetière, calculée dans GIRAF selon un indice de cherté de vie',0,0,'C');
INSERT INTO PTG_ADM.PTG_REF_PRIME (ID_REF_PRIME, NORUBR, LIBELLE, DESCRIPTION, TYPE_SAISIE, IS_CALCULEE, STATUT) VALUES (PTG_S_REF_PRIME.NEXTVAL, 7750,'INDEMNITE D''ACTIVITE','Anciennement prime de cimetière, calculée dans GIRAF selon un indice de cherté de vie',0,0,'CC');

COMMIT;
