----------------------------------------------------------------
-- connecte en PTG_ADM
----------------------------------------------------------------

ALTER TABLE PTG.PTG_DROITS_AGENT DROP COLUMN ID_AGENT_APPROBATEUR;
ALTER TABLE PTG.PTG_DROITS_AGENT DROP COLUMN ID_DROITS_PROFIL;
ALTER TABLE PTG.PTG_DROITS_AGENT ADD (IS_APPROBATEUR NUMBER(1,0) default 0 not null);
ALTER TABLE PTG.PTG_DROITS_AGENT ADD (IS_DELEGATAIRE NUMBER(1,0) default 0 not null);
ALTER TABLE PTG.PTG_DROITS_AGENT ADD (IS_OPERATEUR NUMBER(1,0) default 0 not null);
DROP TABLE PTG.PTG_DROITS_PROFIL;
