----------------------------------------------------------------
-- connecte en PTG_USR
----------------------------------------------------------------

DECLARE
 ID_APPRO_9005138 NUMBER(38,0);
 ID_OPE_9002990 NUMBER(38,0);
 ID_OPE_9005131 NUMBER(38,0);
 ID_APPRO_9003069 NUMBER(38,0);
 ID_DROIT_AGENT NUMBER(38,0);
BEGIN

-- DROITS
select PTG_S_DROIT.NEXTVAL into ID_APPRO_9005138 from dual;
Insert into PTG_ADM.PTG_DROIT (ID_DROIT,ID_AGENT,DATE_MODIFICATION,IS_APPROBATEUR,IS_OPERATEUR,ID_AGENT_DELEGATAIRE,ID_DROIT_APPROBATEUR,VERSION) values (ID_APPRO_9005138,'9005138',to_date('24/07/13','DD/MM/RR'),'1','0','9005131',null,'0');
select PTG_S_DROIT.NEXTVAL into ID_OPE_9002990 from dual;
Insert into PTG_ADM.PTG_DROIT (ID_DROIT,ID_AGENT,DATE_MODIFICATION,IS_APPROBATEUR,IS_OPERATEUR,ID_AGENT_DELEGATAIRE,ID_DROIT_APPROBATEUR,VERSION) values (ID_OPE_9002990,'9002990',to_date('24/07/13','DD/MM/RR'),'0','1',null,ID_APPRO_9005138,'0');
select PTG_S_DROIT.NEXTVAL into ID_OPE_9005131 from dual;
Insert into PTG_ADM.PTG_DROIT (ID_DROIT,ID_AGENT,DATE_MODIFICATION,IS_APPROBATEUR,IS_OPERATEUR,ID_AGENT_DELEGATAIRE,ID_DROIT_APPROBATEUR,VERSION) values (ID_OPE_9005131,'9005131',to_date('24/07/13','DD/MM/RR'),'0','1',null,ID_APPRO_9005138,'0');

select PTG_S_DROIT.NEXTVAL into ID_APPRO_9003069 from dual;
Insert into PTG_ADM.PTG_DROIT (ID_DROIT,ID_AGENT,DATE_MODIFICATION,IS_APPROBATEUR,IS_OPERATEUR,ID_AGENT_DELEGATAIRE,ID_DROIT_APPROBATEUR,VERSION) values (ID_APPRO_9003069,'9003069',to_date('24/07/13','DD/MM/RR'),'1','0',null,null,'0');

--DROITS_AGENTS & DROITS_DROITS_AGENTS
select PTG_S_DROITS_AGENT.NEXTVAL into ID_DROIT_AGENT from dual;
Insert into PTG_ADM.PTG_DROITS_AGENT (ID_DROITS_AGENT,ID_AGENT,CODE_SERVICE,LIBELLE_SERVICE,DATE_MODIFICATION,VERSION) values (ID_DROIT_AGENT,'9003041','DCCA','DSI Service Etudes et Développement',to_date('24/07/13','DD/MM/RR'),'0');
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_APPRO_9005138,ID_DROIT_AGENT);
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_OPE_9002990,ID_DROIT_AGENT);

select PTG_S_DROITS_AGENT.NEXTVAL into ID_DROIT_AGENT from dual;
Insert into PTG_ADM.PTG_DROITS_AGENT (ID_DROITS_AGENT,ID_AGENT,CODE_SERVICE,LIBELLE_SERVICE,DATE_MODIFICATION,VERSION) values (ID_DROIT_AGENT,'9004117','DCCA','DSI Service Etudes et Développement',to_date('24/07/13','DD/MM/RR'),'0');
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_APPRO_9005138,ID_DROIT_AGENT);
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_OPE_9005131,ID_DROIT_AGENT);

select PTG_S_DROITS_AGENT.NEXTVAL into ID_DROIT_AGENT from dual;
Insert into PTG_ADM.PTG_DROITS_AGENT (ID_DROITS_AGENT,ID_AGENT,CODE_SERVICE,LIBELLE_SERVICE,DATE_MODIFICATION,VERSION) values (ID_DROIT_AGENT,'9003305','DCDA','DSI Service de l''Information Géographique',to_date('24/07/13','DD/MM/RR'),'0');
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_APPRO_9005138,ID_DROIT_AGENT);
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_OPE_9005131,ID_DROIT_AGENT);

select PTG_S_DROITS_AGENT.NEXTVAL into ID_DROIT_AGENT from dual;
Insert into PTG_ADM.PTG_DROITS_AGENT (ID_DROITS_AGENT,ID_AGENT,CODE_SERVICE,LIBELLE_SERVICE,DATE_MODIFICATION,VERSION) values (ID_DROIT_AGENT,'9003544','DCBA','DSI Service Infrastructure et Exploitation',to_date('24/07/13','DD/MM/RR'),'0');
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_APPRO_9005138,ID_DROIT_AGENT);
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_OPE_9005131,ID_DROIT_AGENT);

select PTG_S_DROITS_AGENT.NEXTVAL into ID_DROIT_AGENT from dual;
Insert into PTG_ADM.PTG_DROITS_AGENT (ID_DROITS_AGENT,ID_AGENT,CODE_SERVICE,LIBELLE_SERVICE,DATE_MODIFICATION,VERSION) values (ID_DROIT_AGENT,'9004445','DCCA','DSI Service Etudes et Développement ',to_date('24/07/13','DD/MM/RR'),'0');
Insert into PTG_ADM.PTG_DROIT_DROITS_AGENT (ID_DROIT,ID_DROITS_AGENT) values (ID_APPRO_9003069,ID_DROIT_AGENT);

END;

COMMIT;