----------------------------------------------------------------
-- connecte en PTG_ADM
----------------------------------------------------------------

ALTER TABLE PTG_VENTIL_HSUP ADD (M_SUP_25_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_SUP_50_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_DJF_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_DJF_25_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_DJF_50_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_1_MAI_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_NUIT_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_NORMALES_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_COMPLEMENTAIRES_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_SIMPLES_R NUMBER(5,0) DEFAULT 0);
ALTER TABLE PTG_VENTIL_HSUP ADD (M_COMPOSEES_R NUMBER(5,0) DEFAULT 0);
