----------------------------------------------------------------
-- connecte en PTG_ADM
----------------------------------------------------------------

UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7120;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7121;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7123;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7709;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7710;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7720;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7721;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7722;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPRIM' WHERE norubr = 7750;

UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7650;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7651;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7652;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7701 AND STATUT = 'CC';
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7704;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7705;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7708;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7711;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7712;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7713;
UPDATE PTG_ADM.PTG_REF_PRIME SET MAIRIE_PRIME = 'SPPPRM' WHERE norubr = 7731;

COMMIT;